plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.property('mod_version')
group = project.property('maven_group')

base {
    archivesName = project.property('archives_base_name')
}

def mc_version = project.property('minecraft_version')

def loader_version = project.property('loader_version')

def fabric_version = project.property('fabric_version')

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${mc_version}"
    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", mc_version
    inputs.property "loader_version", loader_version
    filteringCharset "UTF-8"
    filesMatching("fabric.mod.json") {
        expand ([
            "version": project.version,
            "minecraft_version": mc_version,
            "loader_version": loader_version
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

tasks.withType(JavaExec).configureEach {
    it.javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from("LICENSE") {
        rename { "${it}" }
    }
}
