org.gradle.jvmargs=-Xmx2G
org.gradle.java.installations.paths=C:/Users/natej/AppData/Local/Java/jdk-25.0.4+7
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_version=0.156.0+26.2
mod_version=1.0.0
maven_group=com.example
archives_base_name=trapTrapdoor
org.gradle.java.home=C:/Users/natej/AppData/Local/Java/jdk-25.0.4+7
